complete tests;remove unnecessary things

diff --git a/qed b/qed
--- a/qed
+++ b/qed
@@ -5,14 +5,8 @@
 
 # Edit-Zone -------------------------------------------
 
-# splitter binary
-SPLITTER=split
-
 # hasher binary
 HASHER=sha256sum
-
-# file compressor binary
-ZIPPER=gzip
 
 # default minimum of QR-version: an integer between 1 and 40
 QR_VERSION=40
@@ -84,12 +78,22 @@ error () {
     exit 1
 }
 
+
 ok () {
     # -> exit status
     # <- $1: ok message
     stderr-msg 1 -n $(green ok) "\t"
     echo $1
 }
+
+
+warning () {
+    # -> exit status
+    # <- $@: all messages passed
+    stderr-msg 1 $(magenta warning) "\t" $@
+    return 0
+}
+
 
 red () {
     # -> ansi-escaped text
@@ -102,6 +106,14 @@ green () {
     # -> ansi-escaped text
     # <- $1: text to colorize green
     echo -e "\033[0;32m$1\033[0m"
+}
+
+
+magenta () {
+
+    # -> ansi-escaped text
+    # <- $1: text to colorize green
+    echo -e "\033[0;35m$1\033[0m"
 }
 
 
@@ -230,7 +242,7 @@ split-data () {
     # <- $1: in
     # <- $2: bytes
     # <- $3: prefix
-    $SPLITTER -b $(($2 - $HEADER_BYTES)) -a ${INDEX_BYTES} "$1" "$3" \
+    split -b $(($2 - $HEADER_BYTES)) -a $INDEX_BYTES "$1" "$3" \
         || error "occurred problem while splitting data in: $(pwd)"
 }
 
@@ -239,34 +251,36 @@ write-header-and-qrencode () {
     # -- write a header to each token and encode it into a QR Code
     #
     # -> void
-    # <- $1: _hash
-    # <- $2: size
-    # <- $3: margin
-    # <- $4: version
-    # <- $5: level
-    # <- $6: fcolor
-    # <- $7: bcolor
+    # <- $1: bytes
+    # <- $2: hash
+    # <- $3: size
+    # <- $4: margin
+    # <- $5: version
+    # <- $6: level
+    # <- $7: fcolor
+    # <- $8: bcolor
     stderr-msg 0 -n "."
     local total=$(printf %0${INDEX_BYTES}d $(ls -1 _ | wc -l))
     local it=1
     for f in $(ls -1 _ | sort); do
         local o="$f.png"
-        local header="$1$(printf %0${INDEX_BYTES}d $it)$total"
-        stderr-msg 0 -n "processing  $1" \
+        local header="$2$(printf %0${INDEX_BYTES}d $it)$total"
+        stderr-msg 0 -n "processing  $2" \
                         "[$(printf %0${INDEX_BYTES}d $it) / $total]  >>  $(pwd)/$o"
 
         # write header to split file
-        echo -n $header | cat - "_/$f" > _/_ && mv _/_ "_/$f"
+        echo -n $header | cat - "_/$f" | head -c $1 > _/_ && mv _/_ "_/$f" \
+            || error "occurred problem while writing header: $header"
 
         # encode each split file into QR Code
         cat "_/$f" | qrencode -8               \
-                              -s $2            \
-                              -m $3            \
-                              -v $4            \
-                              -l $5            \
+                              -s $3            \
+                              -m $4            \
+                              -v $5            \
+                              -l $6            \
                               -o $o            \
-                              --foreground=$6  \
-                              --background=$7  \
+                              --foreground=$7  \
+                              --background=$8  \
             || error "occurred problem while encoding data into QR Code: $(pwd)/$f"
         it=$((it+1))
     done
@@ -340,19 +354,22 @@ encode () {
         error "failed to get QR-max-encoding-byte." \
               "\n\t check if the values of -l, -t, and -V are set correctly."
 
-    # get a hash-id-key for data
-    local _hash=$(hash-id "$2")
-
     # tmp working directory
     t=$(tmp-filepath)
     assert-dir "$t/_"
     cd $t
 
+    # get a hash-id-key for data
+    local hash=$(hash-id $2)
+    [[ ${#hash} -eq $HASH_ID_BYTES ]] \
+        || error "something wrong with hash-id value: $hash"
+
     # split the given buffer if it is large enough
-    split-data "$2" $bytes "$t/_/${_hash}-"
+    split-data "$2" $bytes "$t/_/$hash-"
 
     # try QR-encoding with the generated header
-    write-header-and-qrencode $_hash \
+    write-header-and-qrencode $bytes \
+                              $hash  \
                               $3     \
                               $4     \
                               $5     \
@@ -373,10 +390,10 @@ encode () {
     if [ -n "$1" ]; then
         ls -1 *.png | tar -cf "$1" -T - \
             && ok "$1" \
-            || error "problem occurred while writing to file: $1"
+            || error "occurred problem while writing to file: $1"
     else
         ls -1 *.png | tar -c -T - \
-            || error "problem occurred while writing to stdout"
+            || error "occurred problem while writing to stdout"
     fi
 }
 
@@ -394,6 +411,7 @@ decode-qrcode-image () {
     # <- $1: qrcode image file
     # <- $2: dirname where decoded files are collected
     # <- $3: resize ratio to original
+    rm -f _ __
 
     # resize
     convert -resize "${3}%" $1 __ \
@@ -414,8 +432,9 @@ decode-qrcode-image () {
                  "${header:$((HEADER_BYTES-$INDEX_BYTES)):$INDEX_BYTES}]" \
                  " <<  $(pwd)/$(basename $1)"
     cat _ | tail -c +$((HEADER_BYTES + 1)) > "$2/$header"
-    rm -f __ _
+    rm -f _ __
 }
+
 
 find-hashes-of-uniq-files () {
     # -> many hash strings (blank separated)
@@ -424,19 +443,28 @@ find-hashes-of-uniq-files () {
     echo -n $(find . -size +0c | awk "$awk" | sort | uniq)
 }
 
-merge-decoded-files () {
+
+merge-and-verify-decoded-files () {
     # -> void
     # <- $1: filepath of merged files
-    # <- $2: hash value that the merged file is expected to have
+    # <- $2: hash
     local f="$1/$2"
     ls -1 | grep $2 | sort | xargs cat > $f \
-        || error "problem occurred during merging decoded files: $f"
+        || error "occurred problem during merging decoded files: $f"
 
-    # check if the decoded is valid
-    [[ "$2" == "$(cat $f | hash-id)" ]] \
-        || error "Not matched hash value of file: $f" \
-                 "\n\t expected $2, but got $(cat $f | hash-id)"
+    # check if the merged file is valid
+    local got=$(cat $f | hash-id)
+    if [ "$2" != "$got" ]; then
+        tar -tf $f &> /dev/null \
+            || error "not matched hash value of file: $f" \
+                     "\n\t expected $2, but got $got"
+
+        warning "still looks like a vaild: $f" \
+                "\n\t\t be aware that the hash is different from the original." \
+                "\n\t\t expected $2, but got $got"
+    fi
 }
+
 
 decode () {
     # -- the outermost decoding wrapper function
@@ -464,9 +492,9 @@ decode () {
     # merge files
     local merged=$(tmp-filepath)
     assert-dir $merged
-    for _hash in $(find-hashes-of-uniq-files); do
-        merge-decoded-files $merged $_hash \
-            || error "failed to merge files with expected hash of: $_hash"
+    for hash in $(find-hashes-of-uniq-files); do
+        merge-and-verify-decoded-files $merged $hash \
+            || error "failed to merge files with expected hash of: $hash"
     done
 
     cd "$merged"
@@ -502,16 +530,15 @@ print-help () {
       -d    decode input
       -p    create and play QR Code slideshows after encoding is finished
       -q    open output QR Code images in browser after encoding is finished
-      -z    compress output tarball of QR code
       -v    show in detail how the work is progressing
-      -o    set output file                  (default: '-' for stdout)
+      -o    set output filepath              (default: '-' for stdout)
+      -V    set version of QR Code           (1 to 40, default: $QR_VERSION)
+      -l    set error correction level       (one of [L,M,Q,H], default: $QR_ERROR_CORRECTION)
       -s    set cell size of QR Code         (default: $QR_CELL_SIZE)
       -m    set margin of QR Code            (recommended 4+, default: $QR_MARGIN)
       -1    set foreground color of QR Code  (6-hexadecimal, default: $QR_FOREGROUND)
       -0    set background color of QR Code  (6-hexadecimal, default: $QR_BACKGROUND)
       -r    set resize-ratio if needed       (0-100%, default: $QR_RESIZE_RATIO)
-      -V    set version of QR Code           (1 to 40, default: $QR_VERSION)
-      -l    set error correction level       (one of [L,M,Q,H], default: $QR_ERROR_CORRECTION)
 HELP
     exit 0
 }
@@ -522,14 +549,13 @@ HELP
 # qed main
 # --------------
 # parsing arguments
-while getopts hdpqzvo:s:m:1:0:r:V:l: flag
+while getopts hdpqvo:s:m:1:0:r:V:l: flag
 do
-    case "${flag}" in
+    case "$flag" in
         h) print-help;;
         d) decode=${OPTARG:-set};;
         p) slideshow=${OPTARG:-set};;
         q) view=${OPTARG:-set};;
-        z) zip=${OPTARG:-set};;
         v) verbose=${OPTARG:-set};;
         o) out=${OPTARG};;
         s) size=${OPTARG};;
@@ -570,7 +596,7 @@ if [[ -n $decode ]]; then
     # when used with arguments
     else
         f="$1"
-        [[ ! -e $f ]] && error "filepath not found: $f"
+        [[ -e $f ]] || error "filepath not found: $f"
         if [ -d $f ]; then
             in=$f
         else
@@ -607,7 +633,7 @@ else
     # when used with arguments
     else
         f="$1"
-        [[ ! -e $f ]] && error "filepath not found: $f"
+        [[ -e $f ]] || error "filepath not found: $f"
     fi
 
     # prepare output name (if any). stdout by default
@@ -618,8 +644,8 @@ else
 
     # prepare input file to encode
     in="$(tmp-filepath).tar.gz"
-    cd $(dirname $f) && tar -c $(basename $f) | $ZIPPER -c > $in \
-        || error "problem occurred while archiving file: $f"
+    cd $(dirname $f) && tar -c $(basename $f) | gzip -c3 > $in \
+        || error "occurred problem while archiving file: $f"
 
     encode "$out"      \
            "$in"       \
